version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    links:
      - mysql
    environment:
        MYSQL_ROOT_PASSWORD: '123456'
        MYSQL_USER: 'usuario'
        MYSQL_DATABASE: 'game'
        MYSQL_ROOT_HOST: "mysql"
        MYSQL_ROOT_PORT: "3306"
  redis:
    image: "redis:alpine"
  mysql:
    container_name: python-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: '123456'
        MYSQL_ROOT_HOST: "0.0.0.0"
        MYSQL_DATABASE: 'game'
        MYSQL_USER: 'usuario'
        MYSQL_PASSWORD: '123456'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes: 
        - ./.docker/mysql/dbdata:/var/lib/mysql
    ports: 
        - "3388:3306"
    